#!/bin/bash

get_first_interface_ipv4() {
    env | grep -E "^ETH0+_IP=" | cut -d '=' -f 2
}

get_first_interface_ipv6() {
    env | grep -E "^ETH0+_IP6=" | cut -d '=' -f 2
}

reset_iptables(){
    iptables --flush
    iptables -t nat --flush
}

create_masquerade(){
    if [ -n "${ETH0_MAC}" ]; then
        ipv4="$(get_first_interface_ipv4)"
	    ipv4_private="$(echo $ipv4 | grep -E '^(192\.168|10\.|172\.1[6789]\.|172\.2[0-9]\.|172\.3[01]\.)')"
	    #echo "ipv4 is $ipv4"
	    #echo "ipv4 private is $ipv4_private"
        ipv6="$(get_first_interface_ipv6)"
	    #echo "ipv6 is $ipv6"
        if [ -z "${ipv4_private}" ]; then
	        configure_ipv4_masquerade
        else
            echo "IPV4 MASQUERADE DISABLED" >> /etc/motd
        fi
        if [ -n "${ipv6}" ]; then
	        configure_ipv6_masquerade
        else
            echo "IPV4 MASQUERADE DISABLED" >> /etc/motd
        fi
    fi
}

configure_ipv4_masquerade(){
    iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    echo "IPV4 MASQUERADE ENABLED VIA ETH0" >> /etc/motd
}

configure_ipv6_masquerade(){
    ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    echo "IPV6 MASQUERADE ENABLED VIA ETH0" >> /etc/motd
}

echo "=========================MASQUERADE========================" >> /etc/motd        
reset_iptables
create_masquerade
